// This file was generated by Mendix Business Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazons3connector.actions;

import java.util.ArrayList;
import java.util.List;
import amazons3connector.AmazonHelper;
import amazons3connector.proxies.S3Bucket;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.model.Bucket;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class JAV_GetBuckets extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private IMendixObject __AwsConfigParameter1;
	private amazons3connector.proxies.AwsConfig AwsConfigParameter1;

	public JAV_GetBuckets(IContext context, IMendixObject AwsConfigParameter1)
	{
		super(context);
		this.__AwsConfigParameter1 = AwsConfigParameter1;
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.AwsConfigParameter1 = __AwsConfigParameter1 == null ? null : amazons3connector.proxies.AwsConfig.initialize(getContext(), __AwsConfigParameter1);

		// BEGIN USER CODE
		AmazonS3 s3client = AmazonHelper.GetS3Client(AwsConfigParameter1);
		
		List<Bucket> buckets = s3client.listBuckets();
		List<IMendixObject> s3buckets = new ArrayList<IMendixObject>();
		
		for(Bucket bucket : buckets) {
			s3buckets.add(createBucket(bucket, getContext()).getMendixObject());
		}
		
		return s3buckets;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "JAV_GetBuckets";
	}

	// BEGIN EXTRA CODE
	public static S3Bucket createBucket(Bucket b, IContext c)
	{
		S3Bucket s3b = new S3Bucket(c);
		s3b.setName(b.getName());
		return s3b;
	}
	// END EXTRA CODE
}
