// This file was generated by Mendix Business Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazons3connector.actions;

import java.util.List;
import amazons3connector.AmazonHelper;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.model.Bucket;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class JAV_GetBucket extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __AwsConfigParameter1;
	private amazons3connector.proxies.AwsConfig AwsConfigParameter1;
	private String S3BucketName;

	public JAV_GetBucket(IContext context, IMendixObject AwsConfigParameter1, String S3BucketName)
	{
		super(context);
		this.__AwsConfigParameter1 = AwsConfigParameter1;
		this.S3BucketName = S3BucketName;
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		this.AwsConfigParameter1 = __AwsConfigParameter1 == null ? null : amazons3connector.proxies.AwsConfig.initialize(getContext(), __AwsConfigParameter1);

		// BEGIN USER CODE
		AmazonS3 s3client = AmazonHelper.GetS3Client(AwsConfigParameter1);
		
		// loop through all the buckets until we find one that matches
		List<Bucket> buckets = s3client.listBuckets();
		
		for(Bucket bucket : buckets) {
			if (bucket.getName().equals(S3BucketName)) {
				return JAV_GetBuckets.createBucket(bucket, getContext()).getMendixObject();
			}
		}
		
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "JAV_GetBucket";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
