// This file was generated by Mendix Business Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package testsuite.actions;

import java.util.ArrayList;
import java.util.List;
import amazons3connector.AmazonHelper;
import amazons3connector.proxies.S3SummaryObject;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.model.ListObjectsRequest;
import com.amazonaws.services.s3.model.ObjectListing;
import com.amazonaws.services.s3.model.S3ObjectSummary;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class JAV_GetObjects extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private IMendixObject __AwsConfigParameter1;
	private amazons3connector.proxies.AwsConfig AwsConfigParameter1;
	private IMendixObject __S3BucketParameter1;
	private amazons3connector.proxies.S3Bucket S3BucketParameter1;

	public JAV_GetObjects(IContext context, IMendixObject AwsConfigParameter1, IMendixObject S3BucketParameter1)
	{
		super(context);
		this.__AwsConfigParameter1 = AwsConfigParameter1;
		this.__S3BucketParameter1 = S3BucketParameter1;
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.AwsConfigParameter1 = __AwsConfigParameter1 == null ? null : amazons3connector.proxies.AwsConfig.initialize(getContext(), __AwsConfigParameter1);

		this.S3BucketParameter1 = __S3BucketParameter1 == null ? null : amazons3connector.proxies.S3Bucket.initialize(getContext(), __S3BucketParameter1);

		// BEGIN USER CODE
		AmazonS3 s3client = AmazonHelper.GetS3Client(AwsConfigParameter1);

		List<IMendixObject> s3objects = new ArrayList<IMendixObject>();
		
		ListObjectsRequest listObjectsRequest = new ListObjectsRequest()
			.withBucketName(S3BucketParameter1.getName());
		ObjectListing objectListing;
		
		do {
			objectListing = s3client.listObjects(listObjectsRequest);
			for (S3ObjectSummary os : objectListing.getObjectSummaries()) {
				// create the objects
				S3SummaryObject o = new S3SummaryObject(getContext());
				o.setKey(os.getKey());
				o.setS3Object_S3Bucket(S3BucketParameter1);
				s3objects.add(o.getMendixObject());
				
				AmazonHelper.enhanceObject(o);
			}
			listObjectsRequest.setMarker(objectListing.getNextMarker());
		} while (objectListing.isTruncated());

		return s3objects;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "JAV_GetObjects";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
