// This file was generated by Mendix Business Modeler 5.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazons3connector.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the AmazonS3Connector module

	public static String getHierarchyDelimiter()
	{
		return (String)Core.getConfiguration().getConstantValue("AmazonS3Connector.HierarchyDelimiter");
	}
}