// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazons3connector.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Represents the file contents of the S3 object
 */
public class S3FileDocument extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "AmazonS3Connector.S3FileDocument";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		S3FileDocument_S3Bucket("AmazonS3Connector.S3FileDocument_S3Bucket");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public S3FileDocument(IContext context)
	{
		this(context, Core.instantiate(context, "AmazonS3Connector.S3FileDocument"));
	}

	protected S3FileDocument(IContext context, IMendixObject s3FileDocumentMendixObject)
	{
		super(context, s3FileDocumentMendixObject);
		if (!Core.isSubClassOf("AmazonS3Connector.S3FileDocument", s3FileDocumentMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a AmazonS3Connector.S3FileDocument");
	}

	/**
	 * @deprecated Use 'S3FileDocument.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static amazons3connector.proxies.S3FileDocument initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return amazons3connector.proxies.S3FileDocument.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static amazons3connector.proxies.S3FileDocument initialize(IContext context, IMendixObject mendixObject)
	{
		return new amazons3connector.proxies.S3FileDocument(context, mendixObject);
	}

	public static amazons3connector.proxies.S3FileDocument load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return amazons3connector.proxies.S3FileDocument.initialize(context, mendixObject);
	}

	public static java.util.List<amazons3connector.proxies.S3FileDocument> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<amazons3connector.proxies.S3FileDocument> result = new java.util.ArrayList<amazons3connector.proxies.S3FileDocument>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//AmazonS3Connector.S3FileDocument" + xpathConstraint))
			result.add(amazons3connector.proxies.S3FileDocument.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of S3FileDocument_S3Bucket
	 */
	public final amazons3connector.proxies.S3Bucket getS3FileDocument_S3Bucket() throws CoreException
	{
		return getS3FileDocument_S3Bucket(getContext());
	}

	/**
	 * @param context
	 * @return value of S3FileDocument_S3Bucket
	 */
	public final amazons3connector.proxies.S3Bucket getS3FileDocument_S3Bucket(IContext context) throws CoreException
	{
		amazons3connector.proxies.S3Bucket result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.S3FileDocument_S3Bucket.toString());
		if (identifier != null)
			result = amazons3connector.proxies.S3Bucket.load(context, identifier);
		return result;
	}

	/**
	 * Set value of S3FileDocument_S3Bucket
	 * @param s3filedocument_s3bucket
	 */
	public final void setS3FileDocument_S3Bucket(amazons3connector.proxies.S3Bucket s3filedocument_s3bucket)
	{
		setS3FileDocument_S3Bucket(getContext(), s3filedocument_s3bucket);
	}

	/**
	 * Set value of S3FileDocument_S3Bucket
	 * @param context
	 * @param s3filedocument_s3bucket
	 */
	public final void setS3FileDocument_S3Bucket(IContext context, amazons3connector.proxies.S3Bucket s3filedocument_s3bucket)
	{
		if (s3filedocument_s3bucket == null)
			getMendixObject().setValue(context, MemberNames.S3FileDocument_S3Bucket.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.S3FileDocument_S3Bucket.toString(), s3filedocument_s3bucket.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazons3connector.proxies.S3FileDocument that = (amazons3connector.proxies.S3FileDocument) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "AmazonS3Connector.S3FileDocument";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
