// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amazons3connector.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class Search
{
	private final IMendixObject searchMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "AmazonS3Connector.Search";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		BucketName("BucketName"),
		ObjectKey("ObjectKey");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public Search(IContext context)
	{
		this(context, Core.instantiate(context, "AmazonS3Connector.Search"));
	}

	protected Search(IContext context, IMendixObject searchMendixObject)
	{
		if (searchMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("AmazonS3Connector.Search", searchMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a AmazonS3Connector.Search");

		this.searchMendixObject = searchMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Search.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static amazons3connector.proxies.Search initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return amazons3connector.proxies.Search.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static amazons3connector.proxies.Search initialize(IContext context, IMendixObject mendixObject)
	{
		return new amazons3connector.proxies.Search(context, mendixObject);
	}

	public static amazons3connector.proxies.Search load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return amazons3connector.proxies.Search.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of BucketName
	 */
	public final String getBucketName()
	{
		return getBucketName(getContext());
	}

	/**
	 * @param context
	 * @return value of BucketName
	 */
	public final String getBucketName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.BucketName.toString());
	}

	/**
	 * Set value of BucketName
	 * @param bucketname
	 */
	public final void setBucketName(String bucketname)
	{
		setBucketName(getContext(), bucketname);
	}

	/**
	 * Set value of BucketName
	 * @param context
	 * @param bucketname
	 */
	public final void setBucketName(IContext context, String bucketname)
	{
		getMendixObject().setValue(context, MemberNames.BucketName.toString(), bucketname);
	}

	/**
	 * @return value of ObjectKey
	 */
	public final String getObjectKey()
	{
		return getObjectKey(getContext());
	}

	/**
	 * @param context
	 * @return value of ObjectKey
	 */
	public final String getObjectKey(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.ObjectKey.toString());
	}

	/**
	 * Set value of ObjectKey
	 * @param objectkey
	 */
	public final void setObjectKey(String objectkey)
	{
		setObjectKey(getContext(), objectkey);
	}

	/**
	 * Set value of ObjectKey
	 * @param context
	 * @param objectkey
	 */
	public final void setObjectKey(IContext context, String objectkey)
	{
		getMendixObject().setValue(context, MemberNames.ObjectKey.toString(), objectkey);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return searchMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amazons3connector.proxies.Search that = (amazons3connector.proxies.Search) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "AmazonS3Connector.Search";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
